#!perl

use strict;
use warnings;
use Getopt::Long;
use Proc::ProcessTable::piddler;

sub version{
        print "piddler v. 0.3.0\n";
	}

sub help{
        print '

-h        Print the help.
--help    Print the help.
-v        Print the version info.
--version Print the version info.

-a        Show a_inodes.
-c        Do not show pipe chains.
-d        Do not dedup.
-f        Do not show FIFOs.
-m        Show memory mapped libraries of the REG type.
-n        Do not resolve PTR addresses.
--nc      Disable color.
-p        Do not show pipes.
-r        Show VREG / files.
-t        Show shared libraries.
-u        Do not show unix sockets.
-E        Do not resolve pipe, FIFO, unix socket, and SHM peers.
-H        Do not humanize sizes.
';
	}

# defaults
my $version;
my $help;
my $txt=0;
my $dont_pipe=0;
my $dont_unix=0;
my $vregroot=0;
my $dont_dedup=0;
my $dont_resolv=0;
my $no_color=0;
my $a_inode=0;
my $dont_fifo=0;
my $memreglib=0;
my $dont_pipe_chains=0;
my $dont_peers=0;
my $dont_human_size=0;

# get the commandline options
Getopt::Long::Configure ('no_ignore_case');
Getopt::Long::Configure ('bundling');
GetOptions(
		   'h' => \$help,
		   'help' => \$help,
		   'v' => \$version,
		   'version' => \$version,
		   't' => \$txt,
		   'p' => \$dont_pipe,
		   'u' => \$dont_unix,
		   'E' => \$dont_peers,
		   'H' => \$dont_human_size,
		   'r' => \$vregroot,
		   'd' => \$dont_dedup,
		   'n' => \$dont_resolv,
		   'nc' => \$no_color,
		   'f' => \$dont_fifo,
		   'a' => \$a_inode,
		   'm' => \$memreglib,
		   'c' => \$dont_pipe_chains,
		   );

# print the version info if requested
if ( $version ){
	&version;
	exit;
}

if ( $help ){
	&version;
	&help;
	exit;
}

# real in the list of PIDs
my @PIDs;
foreach my $arg ( @ARGV ){
	my @possibles=split(/\,/, $arg);

	foreach my $pid ( @possibles ){
		if ( $pid !~ /^[0-9]+$/ ){
			die $pid." does not appear to be a PID.\n";
		}
		push( @PIDs, $pid );
	}
}

# XOR the -t if needed
if ( defined( $ENV{PIDDLER_txt} ) ){
	$txt = $txt ^ ( $ENV{PIDDLER_txt} ? 1 : 0 );
}
# XOR the -p if needed
if ( defined( $ENV{PIDDLER_dont_pipe} ) ){
	$dont_pipe = $dont_pipe ^ ( $ENV{PIDDLER_dont_pipe} ? 1 : 0 );
}
# XOR the -u if needed
if ( defined( $ENV{PIDDLER_dont_unix} ) ){
	$dont_unix = $dont_unix ^ ( $ENV{PIDDLER_dont_unix} ? 1 : 0 );
}
# XOR the -r if needed
if ( defined( $ENV{PIDDLER_vregroot} ) ){
	$vregroot = $vregroot ^ ( $ENV{PIDDLER_vregroot} ? 1 : 0 );
}
# XOR the -m if needed
if ( defined( $ENV{PIDDLER_memreglib} ) ){
	$memreglib = $memreglib ^ ( $ENV{PIDDLER_memreglib} ? 1 : 0 );
}
# XOR the -a if needed
if ( defined( $ENV{PIDDLER_a_inode} ) ){
	$a_inode = $a_inode ^ ( $ENV{PIDDLER_a_inode} ? 1 : 0 );
}
# XOR the -f if needed
if ( defined( $ENV{PIDDLER_dont_fifo} ) ){
	$dont_fifo = $dont_fifo ^ ( $ENV{PIDDLER_dont_fifo} ? 1 : 0 );
}
# XOR the -d if needed
if ( defined( $ENV{PIDDLER_dont_dedup} ) ){
	$dont_dedup = $dont_dedup ^ ( $ENV{PIDDLER_dont_dedup} ? 1 : 0 );
}
# XOR the -c if needed
if ( defined( $ENV{PIDDLER_dont_pipe_chains} ) ){
	$dont_pipe_chains = $dont_pipe_chains ^ ( $ENV{PIDDLER_dont_pipe_chains} ? 1 : 0 );
}
# XOR the -E if needed
if ( defined( $ENV{PIDDLER_dont_peers} ) ){
	$dont_peers = $dont_peers ^ ( $ENV{PIDDLER_dont_peers} ? 1 : 0 );
}
# XOR the -H if needed
if ( defined( $ENV{PIDDLER_dont_human_size} ) ){
	$dont_human_size = $dont_human_size ^ ( $ENV{PIDDLER_dont_human_size} ? 1 : 0 );
}
# XOR the -n if needed
if ( defined( $ENV{PIDDLER_dont_resolv} ) ){
	$dont_resolv = $dont_resolv ^ ( $ENV{PIDDLER_dont_resolv} ? 1 : 0 );
}
# same for the no color, which per the NO_COLOR spec is any non-empty value
if (
	( defined( $ENV{NO_COLOR} ) ) &&
	( $ENV{NO_COLOR} ne '' )
	){
        $no_color = $no_color ^ 1;
}
# disable the color if requested
if ( $no_color ){
        $ENV{ANSI_COLORS_DISABLED}=1;
}else{
        # Term::ANSIColor drops the color for any defined NO_COLOR, so it
        # has to go for the XOR above to be able to turn the color back on
        delete( $ENV{NO_COLOR} );
}


my $ppp=Proc::ProcessTable::piddler->new(
										 {
										  txt=>$txt,
										  unix=>( $dont_unix ? 0 : 1 ),
										  pipe=>( $dont_pipe ? 0 : 1 ),
										  a_inode=>$a_inode,
										  fifo=>( $dont_fifo ? 0 : 1 ),
										  vregroot=>$vregroot,
										  dont_dedup=>$dont_dedup,
										  dont_resolv=>$dont_resolv,
										  memreglib=>$memreglib,
										  pipe_chains=>( $dont_pipe_chains ? 0 : 1 ),
										  peers=>( $dont_peers ? 0 : 1 ),
										  human_size=>( $dont_human_size ? 0 : 1 ),
										  }
										 );

print $ppp->run( \@PIDs );
exit 0;

=head1 NAME

piddler - Display all process table, open files, and network connections for a PID.

=head1 SYNOPSIS

piddler [B<-a>] [B<-c>] [B<-d>] [B<-f>] [B<-m>] [B<-n>] [B<--nc>] [B<-p>] [B<-r>] [B<-t>] [B<-u>] [B<-E>] [B<-H>] <PID>[,<PID>...]

piddler [B<-h>|B<--help>]

piddler [B<-v>|B<--version>]

=head1 FLAGS

=head2 -a

Show a_inodes.

=head2 -c

Do not show pipe chains.

=head2 -d

Do not dedup.

=head2 -f

Do not show FIFOs.

=head2 -m

Show memory mapped libraries of the REG type.

=head2 -n

Do not resolve PTR addresses

=head2 --nc

Disable color..

=head2 -p

Do not show pipes.

=head2 -r

Show show VREG / files.

=head2 -t

Show shared libraries.

=head2 -u

Do not show unix sockets.

=head2 -E

Do not resolve pipe, FIFO, unix socket, and SHM peers.

=head2 -H

Do not humanize sizes.

=head1 ENVIRONMENTAL VARIABLES

These are used for XORing the corresponding flags. So setting
one to 1 has the same effect as passing the flag, and passing
the flag as well XORs it back off.

=head2 NO_COLOR

If set to a non-empty value, color will be disabled, the same
as B<--nc>.

=head2 PIDDLER_a_inode

If set to 1, a_inode types will be shown, the same as B<-a>.

=head2 PIDDLER_dont_fifo

If set to 1, FIFOs will not be shown, the same as B<-f>.

=head2 PIDDLER_memreglib

If set to 1, memory mapped libraries with the type REG will be
shown, the same as B<-m>.

=head2 PIDDLER_txt

If set to 1, libraries with the TXT type will be shown, the
same as B<-t>.

=head2 PIDDLER_dont_pipe

If set to 1, pipes will not be shown, the same as B<-p>.

=head2 PIDDLER_dont_pipe_chains

If set to 1, pipe chains will not be shown, the same as B<-c>.

=head2 PIDDLER_dont_unix

If set to 1, unix sockets will not be shown, the same as B<-u>.

=head2 PIDDLER_dont_peers

If set to 1, pipe, FIFO, unix socket, and SHM peers will not
be resolved, the same as B<-E>.

=head2 PIDDLER_dont_human_size

If set to 1, sizes will be printed as the raw number of
bytes, the same as B<-H>.

=head2 PIDDLER_vregroot

If set to 1, VREG / will be shown, the same as B<-r>.

=head2 PIDDLER_dont_dedup

If set to 1, duplicate file handles are not removed, the same
as B<-d>.

=head2 PIDDLER_dont_resolv

If set to 1, PTR addresses will not be resolved for
network connections, the same as B<-n>.

=head1 PIPE CHAINS

By default a section is shown for the pipelines the process is a part
of, with the commands printed in the order the data flows through them.
B<-c> turns this off.

    PIPE CHAINS
    ps auxw(4821) | grep foo(4822) | wc -l(4823)

Commands longer than 40 characters are truncated. Any process that can
not be looked up, such as one belonging to another user when not running
as root, is shown as a ?. A process may sit on more than one pipe, so at
most 16 chains are shown for any one of them.

Tying the two ends of a pipe together requires a system wide lsof, so it
is only run for processes that actually have a pipe open, and only once
no matter how many PIDs are given.

The direction of a pipe is taken from the r and w access characters when
lsof reports them. Systems such as FreeBSD report pipes as being open
read/write instead, in which case the descriptor number is used, 0 being
the input and 1 and 2 being the output. On those systems that means only
pipes on stdin, stdout, and stderr may be chained together.

=head1 PIPE, FIFO, UNIX SOCKET, AND SHM PEERS

The command holding the far end of a pipe, FIFO, unix socket, or shared
memory object is appended to the one in question, so B<-p>, B<-f>, and
B<-u> decide whether it is seen at all for those. B<-E> turns just this
off.

    7u  unix 0xfffff80022630400 0             ->0xfffff80022635000 (dbus-daemon --session(51092))
    14u unix 0xfffff80052dee800 0             /tmp/dbus-nWRW4XDDoD (xfce4-panel(63471))
    3r  FIFO 0xe6               0t0 299839014 /tmp/testfifo (cat(12593))
    17u SHM                     288876   0    (firefox -contentproc...(7375, 24844, 32640, + 26 more))

The far end is found either by way of the endpoint this one points at,
by way of whatever points at this one, or by way of what else has the
same one open. The second is what covers the unix sockets lsof names
after the path they are bound to, such as the accepted end of a
connection, and the third the FIFOs, shared memory objects, and pipes
that both ends hold the same object for.

Commands longer than 40 characters are truncated. A endpoint whose far
end can not be looked up, such as one held by another user's process when
not running as root, is shown as a ?. Nothing is shown for one that has
no far end to speak of, such as a unix socket that is only bound and
listening or a FIFO no one else has open.

A endpoint may be held by any number of other processes, such as a shared
memory object inherited across a pile of forks, so the PIDs are gathered
up under the command they are running and at most 8 commands and 8 PIDs
per command are printed, with the rest noted as a count.

Tying the two ends together requires a system wide lsof, which is only
done when a pipe, FIFO, unix socket, or shared memory object is actually
going to be printed, and only once no matter how many PIDs are given.

Unix sockets are only tied together on systems whose lsof points at the
far end of one, such as FreeBSD.

=head1 FILE HANDLE DEDUPING

By default it checks if file handles are open in the same
mode more than once. If it finds one of these + is appended
to the value in the FD column.

The following are also RW filehandles.

   u
   uw
   ur

Shared memory objects are rolled up as well. A process may hold a great
many that print the same, anonymous ones having nothing to tell them
apart but their size and what else holds them, so only the first of them
is printed, with the number left off tacked onto the FD. B<-d> turns this
off along with the rest of the deduping.

    40u+43 SHM  262.144k

=cut

